version: 1
runners:
  Machine:
    config-id: 2
images:
  image:
    image: node:20
    auth:
      username: santhosh270
      password: Catalyst@test123
jobs:
  Deploy_Client_Functions:
    runner: Machine
    image: image
    steps:
      - export VERCEL_TOKEN=mUikWMRzX2PeXPj1L1dFehea
      - export VERCEL_ORG_ID=team_4lG0cmXSKTk9frWkvOV6i2aP
      - export VERCEL_PROJECT_ID=prj_MMz91bA3Rdw3oU0U8lxEx0RVMnxS
      - printenv
      - npm install -g vercel
      - vercel build
      - vercel --version
      - vercel deploy --prebuilt --token=mUikWMRzX2PeXPj1L1dFehea
stages:
  - name: test
    jobs:
      - Deploy_Client_Functions
variables:
  VercelToken: DWkAIYRcGfsaZqkJmK2LtD3u